export const routes = {
  sitio_web: "/",
  equipo: "/paginaweb/equipo",
  paginawebcitas: "/paginaweb/citas",
  editarperfil: "/paginaweb/editareditarperfil",
  cambiopassword: "/paginaweb/cambiodepassword",
  login: "/paginaweb/inicio_de_sesion/login",
  registro: "/paginaweb/inicio_de_sesion/registro",
  olvidarpassword: "/paginaweb/inicio_de_sesion/olvidarpassword",
  dashboard: "/dashboard",
  pacientes: "/dashboard/pacientes",
  organizaciones: "/dashboard/pacientes/organizaciones",
  citas: "/dashboard/citas/calendario",
  usuarios: "/dashboard/usuarios",
  roles: "/dashboard/roles",
  eventos_del_sistema: "/dashboard/eventos_del_sistema",
  tratamientos: "/dashboard/tratamientos",
  tipos_de_tratamiento: "/dashboard/tratamientos/tipos_de_tratamiento",
};
