export const routes = {
  sitio_web: "/",
  acceso_no_autorizado: "/paginaweb/acceso_no_autorizado",
  equipo: "/paginaweb/equipo",
  paginawebcitas: "/paginaweb/citas",
  editarperfil: "/paginaweb/inicio_de_sesion/editarperfil",
  cambiopassword: "/paginaweb/inicio_de_sesion/cambiodepassword",
  login: "/paginaweb/inicio_de_sesion/login",
  registro: "/paginaweb/inicio_de_sesion/registro",
  olvidarpassword: "/paginaweb/inicio_de_sesion/olvidarpassword",
  dashboard: "/dashboard",
  pacientes: "/dashboard/pacientes",
  odontograma: "/dashboard/pacientes/odontograma",
  organizaciones: "/dashboard/organizaciones",
  citas: "/dashboard/citas/calendario",
  usuarios: "/dashboard/usuarios",
  roles: "/dashboard/usuarios/roles",
  eventos_del_sistema: "/dashboard/usuarios/eventos_del_sistema",
  tratamientos: "/dashboard/tratamientos",
  tipos_de_tratamiento: "/dashboard/tratamientos/tipos_de_tratamiento",
  deudas: "/dashboard/deudas",
  reportepacientes: "/dashboard/pacientes/reportes",
  reportecitas: "/dashboard/citas/reportes",
  reporteusuarios: "/dashboard/usuarios/reportes",
  reportestratamiento: "/dashboard/tratamientos/reportes",
  configurarimportardatos: "/dashboard/configuracion/importar",
};
